[workspace]
authors = ["Jacob Williams <jacobwilliams@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "env"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
ujson = ">=5.11.0,<6"

[pypi-dependencies]
python-rapidjson = ">=1.23, <2"
